@baseUrl = http://localhost:1122/api/v1
@contentType = application/json

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email":"nanaakuffu@gmail.com",
    "password":"password"
}

###
@token=Bearer {{login.response.body.data.token}}

###
GET {{baseUrl}}/users
Authorization: {{token}}

###
POST {{baseUrl}}/users
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "first_name":"Nana Abeiku",
    "last_name":"Andam",
    "email":"nanabaahakuffu@gmail.com",
    "password":"password"
}

###
{{baseUrl}}/authors/1
Authorization: {{token}}

###
POST {{baseUrl}}/authors
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "first_name":"Abeiku",
    "last_name":"Baah Akuffu"
}

###
{{baseUrl}}/books

###
POST {{baseUrl}}/books
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "title": "The man called Nana",
    "year":2021
}
###
GET {{baseUrl}}/avatar/1